site_name: BDTsim
site_author: Matthias Lohr
copyright: Copyright &copy; 2020 Matthias Lohr
theme: readthedocs
repo_url: https://gitlab.com/MatthiasLohr/bdtsim

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Commands: commands.md
  - Protocols: protocols.md
  - Environments: environments.md
  - Data Providers: dataproviders.md
  - API Documentation: https://matthiaslohr.gitlab.io/bdtsim/api/bdtsim/
